version: '2.3'

services:

  notebooks:
    image: jupyter/tensorflow-notebook

    volumes:
      - ./:/code
      - ./data:/data
      - ./models:/models  

    working_dir: /code/notebooks

    ports:
      - 8888:8888

    command: jupyter lab --no-browser --allow-root --ip 0.0.0.0 --NotebookApp.custom_display_url=http://localhost:8888

  ipython-shell:
    build: .
    runtime: nvidia

    volumes:
      - ./:/code
      - ./data:/data
      - ./models:/models

    working_dir: /code/pilotnet

    ports:
      - 6006:6006

    stdin_open: true
    tty: true

    command: ipython --TerminalInteractiveShell.editing_mode=vi

  augment-images:
    build: .
    runtime: nvidia

    volumes:
      - ./:/code
      - ./data:/data
      - ./models:/models

    working_dir: /code

    ports:
      - 6006:6006

    stdin_open: true
    tty: true

    command: bash pilotnet/scripts/data-augmentation.sh

  train:
    build: .
    runtime: nvidia

    volumes:
      - ./:/code
      - ./data:/data
      - ./models:/models

    working_dir: /code

    ports:
      - 6006:6006

    stdin_open: true
    tty: true

    command: bash pilotnet/scripts/train.sh

  infer:
    build: .
    runtime: nvidia

    volumes:
      - ./:/code
      - ./data:/data
      - ./models:/models
      - /tmp/.X11-unix:/tmp/.X11-unix

    working_dir: /code

    ports:
      - 6006:6006
      - 4567:4567 

    stdin_open: true
    tty: true


    command: python3 -m pilotnet.run --export_dir /models/pilotnet_rel/export/pilotnet_relational/1550798369   

